apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::963964593909:role/eksctl-eksctl-demo-nodegroup-ng-b-NodeInstanceRole-XC26V9W8SWLI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
    - system:masters
    rolearn: arn:aws:iam::963964593909:role/UdacityFlaskDeployCBKubectlRole
    username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-02T04:42:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1598"
  uid: ad24a760-2cbb-4ea1-b50c-70b6780b6b5b
